spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mydb?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver




profile: 'E:/fileManage/'